TRUNCATE TABLE main.users RESTART IDENTITY CASCADE;
TRUNCATE TABLE main.roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE main.permissions RESTART IDENTITY CASCADE;
TRUNCATE TABLE main.user_roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE main.user_permissions RESTART IDENTITY CASCADE;
TRUNCATE TABLE main.role_permissions RESTART IDENTITY CASCADE;
